spring:
  application:
    name: MAC-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pevent
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
  jpa:
    properties:
      open-in-view: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

cloud:
  discovery:
    enabled: true

server:
  port: 8085
